# render.yaml

services:
  - type: web
    name: app-test
    env: python
    plan: free
    
    # 定义构建流程
    buildCommand: |
      # 强制重新构建 v2
      # 1. 更新系统包管理器并安装Ghostscript
      apt-get update && apt-get install -y ghostscript
      
      # 2. 安装Python依赖
      pip install -r requirements.txt
      
      # 3. 编译核心逻辑并清理源代码
      python setup.py build_ext --inplace && rm secure_core.py
    
    # 启动应用的命令
    startCommand: "gunicorn app:app"
