# render.yaml (修正版)

services:
  - type: web
    name: app-test
    env: docker   # 告诉Render使用Dockerfile
    plan: free    # 或者你需要的付费计划
    # 当env为docker时，以下所有内容都应该被删除：
    # buildCommand: ... (删除)
    # startCommand: ... (删除)
